#!/bin/sh
##       ____             __                               ##
##      / __ \_________ _/ /_____                          ##
##     / / / / ___/ __ `/ //_/ _ \                         ##
##    / /_/ / /  / /_/ / ,< /  __/  Clay Gomera (Drake)    ##
##   /_____/_/   \__,_/_/|_|\___/   My custom dwm build    ##


pkill pipewire
pkill pipewire-pulse
pkill wireplumber
pipewire &
pipewire-pulse &
wireplumber &

/usr/libexec/polkit-gnome-authentication-agent-1 &
dwmblocks &
sh "$HOME"/.fehbg &
unclutter --hide-on-touch &
herbed &
picom --config "$HOME/.config/picom/picom.conf" &
